### ISSUE TITLE
Speed up restarting the level.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [beat-game/beat-game#64]
After the alien dies add those possibilities:

1. When the user taps on the screen, **immediately** cancel the dying screen and restart the level. Don't let the dying-animation go on but instantly start another attempt.
2. If the user doesn't press any buttons, at all, let the dying animation play and then return to whereever you want to return.

This is an super important issue!
Beat Game is a game where you die **a lot**, and having to wait every time you die is horrible.

When dying, I actually started to click on the "back"-button to exit out to the menu, and went trough the whole stage selection process just because it was WAY faster than waiting for the intended route.

**Comment by pserwylo** [comment]
Ha!

> Beat Game is a game where you die **a lot**

I should make that the first line in the game description 😄.

But that is a good point. I think we could probably get rid of the entire notion of a second screen after you die. I think we could just fade in over the top of the screen another layer which includes the score and achievements (see v0.3.0 via GitHub releases for achievements). Then, we can show a very prominent "Restart" button, and some less prominent "Change level" or "Main menu" buttons.

**Comment by Glitchy-Tozier** [comment]
> I should make that the first line in the game description :smile:.

That would make a lot of sense!  xD

> Then, we can show a very prominent "Restart" button, and some less prominent "Change level" or "Main menu" buttons.

That would be a big improvement. 
I'm not sure what other people might think of this, but personally I don't even want to bother with the dying animation. (it's nice, but it takes time and seeing it >30 times in 30 minutes gets a bit redundant.)

That is why i think in addition to that…
> Then, we can show a very prominent "Restart" button, and some less prominent "Change level" or "Main menu" buttons.

…the entire dying-screen should act as an instant restart button. No indication required. People will discover it quickly, I'm certain of it. (I myself kept clicking on it trying to speed up the dying process.)

**Comment by pserwylo** [comment]
Okay, here we go:

![Screenshot_2021-03-07_15-07-22](https://user-images.githubusercontent.com/248565/110228655-db69ef80-7f56-11eb-87ab-791f72e80f3e.png)

This is working really well for me. For an additional nicety, it just so happened the game was programmed in such a way that the ghost continues to move upwards after the level completes! So this menu stays here and the ghost slowly ascends.

Some other notes:
* It lowers the volume of the level to 40%...
* ... but keeps playing the song, so there is no abrupt end, and you can actually listen to what the rest of the level would have sounded like had you stayed alive which I enjoy.
* Adds a black background
* Removes "The End"
* Only shows the distance / score if it is a high score (because they are still visible in the bottom left corner).
* If there are too many achievements earned, the screen will be able to be scrolled.
* If you hit "Replay", then it is actually a lot faster because it has already loaded the level information from disk

**Comment by pserwylo** [comment]
Okay, so I have a v0.5.0 version ready to tag, will do so once F-Droid builds and released v0.4.0. Feel free to check out the debug build here:

https://github.com/beat-game/beat-game/releases/tag/untagged-44ed661b6d0314a50277

**Comment by Glitchy-Tozier** [comment]
I try to only use stuff from F-droid as it's at least a little bit safer (from what I understand), so I'll ty it out once it's released  :)

**Comment by pserwylo** [comment]
Alright, v0.5.0 now out on F-Droid which should fix this. Let me know how it goes. Feel free to continue discussing here or start a new issue/discussion of there is something else you'd like to recommend regarding this.

**Comment by Glitchy-Tozier** [comment]
Unfortunately i can't, Fdroid is acting weird.
Once it's back to normal, i'll try it out.

**Comment by Glitchy-Tozier** [comment]
Okay, It's way better now!!
