### ISSUE TITLE
Add pause screen to the game

### ISSUE THREAD

**Issue by Thewisem** [beat-game/beat-game#73]
When the game starts, it doesn't have a pause function which id very disturbing as it is one of the basics of a game. But anyways mind adding a pause function to the game so that I can pause during gameplay

**Comment by pserwylo** [comment]
Yeah, makes sense. There is actually pause functionality but only on the desktop version I use for debugging. This was so that I could pause to check out how certain parts of the level rendered. It will be relatively trivial to add a button to the main game (e.g. top left corner) which pauses the game.

Indeed, once paused, the user should have the option to:
* Resume
* Restart
* Change level
* Return to main menu

**Comment by Thewisem** [comment]
You could use back as a option to pause if you want as well

**Comment by Thewisem** [comment]
When changing between apps (aka) multiscreen the app should automatically stop itself in the pause screen (just saying)

**Comment by pserwylo** [comment]
Alrighty, I've tagged a v0.7.0 version with the pause screen added. F-Droid is currently building the v0.6.0 version, and then after that it will start building v0.7.0. Thanks for your feedback! Once it gets released, please feel free to comment here if you have any feedback. You can also test the debug build from the releases page if you are feeling adventurous

![pause-menu](https://user-images.githubusercontent.com/248565/111768783-78843b00-88fc-11eb-9f42-1ff5445ee30c.png)

![pause-screen](https://user-images.githubusercontent.com/248565/111768803-7f12b280-88fc-11eb-9727-dd1d669975b8.png)
